import React, { useEffect } from "react";

const Terms = () => {
  useEffect(() => {
    // Smooth scroll to top
    window.scrollTo({
      top: 0,
      left: 0,
      behavior: "smooth",
    });
  }, []);
  return (
    <div className="min-h-screen bg-white p-4 sm:p-8">
      <div className="max-w-4xl mx-auto bg-[#F5F9FF]  p-6 rounded-lg shadow-lg mt-14">
        <h1 className="text-5xl font-meuthanies   text-center text-balck mb-6">
          Terms and Conditions
        </h1>
        <p className="text-md text-black">
          This document is an electronic record in terms of the Information
          Technology Act, 2000, and rules thereunder as applicable and the
          amended provisions pertaining to electronic records in various
          statutes as amended by the Information Technology Act, 2000. This
          electronic record is generated by a computer system and does not
          require any physical or digital signatures.
        </p>
        <div>
          <h2 className="text-2xl  font-meuthanies text-customBlue mt-10">1. Terms</h2>
          <p className="text-md text-black mt-2">
            By accessing or using the website www.paxowealth.com (“Website”) or
            the mobile application (“Application”), both collectively referred
            to as the “Platform”, you agree to be bound by these terms of
            service, the privacy policy, and all applicable laws and
            regulations. You agree that you are responsible for compliance with
            any applicable laws pertaining to your use or access to the
            Platform. If you do not agree with any of these terms, you must
            discontinue your use of the Platform. References to terms such as
            “you” and “your” in these Terms of Service shall mean the user(s)
            who access and/or use the Platform, and terms such as “us”, “we”,
            and “our” shall mean Paxo Wealth Private Limited (“PWPL”).
          </p>{" "}
        </div>
        <div>
          <div className="  text-black">
            <h2 className="text-2xl  font-meuthanies text-customBlue mt-10">2. Use License</h2>
            <p className="text-md mt-2">
              The Platform is owned, administered, and monitored by PWPL having
              CIN UXXXXXXXXXXXXX and its registered office at [Company Address].
              The content, text, and logos contained on the Platform are the
              proprietary information of PWPL. Subject to compliance with these
              Terms of Service and payment of fees (if and as applicable), PWPL
              grants you a non-transferable, non-exclusive license to access
              and/or use the Platform for your personal, non-commercial use.
            </p>
            <p className="text-md mt-4">You shall not:</p>
            <ul className="list-disc list-inside space-y-2 mt-2 p-4">
              <li>
                Copy, distribute, display, download, reproduce, modify, repost,
                transmit, or use any part of the Platform without the prior
                written consent of PWPL.
              </li>
              <li>
                Use the materials for any commercial purpose or for any public
                display (commercial or non-commercial).
              </li>
              <li>
                Attempt to decompile or reverse engineer any software contained
                on the Platform.
              </li>
              <li>
                Remove any copyright or other proprietary notations from any
                materials on the Platform.
              </li>
            </ul>
            <p className="text-md mt-4">
              Any such action may constitute a violation of applicable laws.
              Your right to access the Platform shall automatically terminate if
              you violate any of these restrictions and may also be terminated
              by PWPL at any time.
            </p>
          </div>
        </div>
        <div>
          <h2 className="text-2xl  font-meuthanies text-customBlue  mt-10">
            3. Disclaimer
          </h2>
          <p className="text-md  mt-2">
            The materials on the Platform are provided on an “as is” basis. PWPL
            makes no warranties, expressed or implied, and hereby disclaims and
            negates all other warranties including, without limitation, implied
            warranties or conditions of merchantability, fitness for a
            particular purpose, or non-infringement of intellectual property or
            other violation of rights.
          </p>
          <p className="text-md  mt-2">
            Further, PWPL does not warrant or make any representations
            concerning the accuracy, likely results, or reliability of the use
            of the materials on the Platform or otherwise relating to such
            materials or on any sites linked to this site.
          </p>{" "}
        </div>
        <div>
          <h2 className="text-2xl  font-meuthanies text-customBlue  mt-4">4. Services</h2>
          <p className="text-md  mt-2">
            If you choose to avail any services from PWPL, you agree and
            acknowledge that you may be required to execute an agreement with
            PWPL, and subject to you being successfully onboarded as a client,
            your rights and obligations with PWPL for availing such services
            will be governed by the terms of the aforementioned agreements.
          </p>{" "}
        </div>
        <div>
          <h2 className="text-2xl  font-meuthanies text-customBlue  mt-10">
            5. Limitations
          </h2>
          <p className="text-md  mt-2">
            In no event shall PWPL be liable for any damages (including, without
            limitation, damages for loss of data or profit, or due to business
            interruption) arising out of the use or inability to use the
            materials on the Platform, even if PWPL or an authorized
            representative of PWPL has been notified of the possibility of such
            damage. PWPL shall not be liable for any damages caused to your
            computer, software, or other equipment due to the use of the
            Platform.
          </p>
          <p className="text-md  mt-2">
            PWPL shall have the right to be indemnified against all suits,
            actions, costs, and damages that may arise on account of the misuse
            or misrepresentation of the contents of the Platform by you.
          </p>
        </div>

        <div>
          <h2 className="text-2xl  font-meuthanies text-customBlue  mt-10">
            6. Accuracy of Materials
          </h2>
          <p className="text-md  mt-2">
            The materials appearing on the Platform could include technical,
            typographical, or photographic errors. PWPL does not warrant that
            any of the materials on its Platform are accurate, complete, or
            up-to-date. PWPL may make changes to the materials contained on its
            Platform at any time without notice. However, PWPL does not make any
            commitment to update the materials on the Platform.
          </p>
        </div>
        <div>
          <h2 className="text-2xl  font-meuthanies text-customBlue mt-10">
            7. External Links
          </h2>
          <p className="text-md  mt-2">
            PWPL has not reviewed all of the sites linked to the Platform and is
            not responsible for the contents of any such third-party linked
            site. The inclusion of any link does not imply endorsement by PWPL
            of such sites. Use of any such linked website is at your own risk.
            You are required to read and understand the terms of usage of the
            respective website and shall be governed by the same. PWPL shall not
            be liable for any damages or penalties arising out of the usage of
            such websites.
          </p>
        </div>
        <div>
          <h2 className="text-2xl  font-meuthanies text-customBlue mt-10">
            8. Modifications
          </h2>
          <p className="text-md  mt-2">
            PWPL may revise these terms of service for the Platform at any time
            without notice. By using the Platform, you agree to be bound by the
            version of these terms of service appearing on the Platform as on
            the relevant date.
          </p>
        </div>
        <div>
          <h2 className="text-2xl  font-meuthanies text-customBlue mt-10">
            9. Governing Law{" "}
          </h2>
          <p className="text-md  mt-2">
            These terms and conditions are governed by and construed in
            accordance with the laws of India. Any dispute arising out of these
            Terms of Service shall be referred to arbitration under the
            Arbitration and Conciliation Act, 1996, by a mutually appointed sole
            arbitrator. The seat and venue of the arbitration shall be
            Bangalore, and the proceedings shall be in English. Subject to the
            foregoing, all disputes under these Terms of Service shall be
            subject to the exclusive jurisdiction of the courts in Bangalore.
          </p>
        </div>
        <div>
          <h2 className="text-2xl  font-meuthanies text-customBlue mt-10">
            10. Confidentiality
          </h2>
          <p className="text-md  mt-2">
            PWPL agrees to handle all information provided by you with utmost
            care and confidentiality in accordance with applicable regulations
            and prescribed industry standards. Similarly, you agree to treat all
            information provided to you by PWPL as confidential and shall not
            disclose it to any third party without prior written consent from
            PWPL. However, if required by an appropriate government authority or
            by applicable law, PWPL may disclose your confidential information
            without prior notice.
          </p>
        </div>
        <div>
          <h2 className="text-2xl  font-meuthanies text-customBlue mt-10">
            11. Privacy Policy
          </h2>
          <p className="text-md  mt-2">
            Please review our Privacy Policy to understand what kind of
            information we gather from you and the specific measures we take to
            protect your personal information. The Privacy Policy is hereby
            incorporated into these terms of service by reference.
          </p>
        </div>
        <div>
          <h2 className="text-2xl  font-meuthanies text-customBlue mt-10">
            12. Miscellaneous
          </h2>
          <p className="text-md  mt-2">
            PWPL’s failure to enforce any provision of these Terms of Service
            shall not be deemed to be a waiver of such provision nor of the
            right to enforce such provision.
          </p>
        </div>
        <div>
          <h2 className="text-2xl  font-meuthanies text-customBlue mt-10">
            13. Contact Us
          </h2>
          <p className="text-md  mt-2">
            If you have any questions regarding these Terms of Service, please
            write to us at{" "}
            <a href="mailto:support@paxowealth.com" className="text-blue-500">
              support@paxowealth.com
            </a>
          </p>
        </div>
      </div>
    </div>
  );
};

export default Terms;
